### ISSUE TITLE
DCNv2 make.sh? a problem

### ISSUE THREAD

**Issue by yinhai86924** [xingyizhou/CenterTrack#90]
nvcc fatal   : Unsupported gpu architecture 'compute_75' error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1 this problem is solved but I have another question when I run the demo.py 
:
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /tmp/pip-req-build-808afw3c/aten/src/THC/THCCachingHostAllocator.cpp:278

**Comment by yinhai86924** [comment]
I  install pytorch version 1.4 again,  this problem is solved.

**Comment by bryanbocao** [comment]
Try using Docker:
https://github.com/bryanbocao/CenterTrack/blob/master/readme/Docker.md
https://github.com/xingyizhou/CenterTrack/pull/290

# Run CenterTrack using Docker

### DCNv2 Compilation Issue Fixed
```
docker pull bryanbocao/centertrack
docker run -d --ipc=host --shm-size=16384m -it -v /:/share --gpus all --network=bridge bryanbocao/centertrack /bin/bash
docker ps -a
```

Check ```<CONTAINER_ID>```:
```
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                       PORTS                NAMES
89bb79551ccb   bryanbocao/centertrack   "/usr/local/bin/nvid…"   49 seconds ago   Up 38 seconds                6006/tcp, 8888/tcp   competent_northcutt
```
```
docker exec -it <CONTAINE_ID> /bin/bash
```

```
docker exec -it 89bb79551ccb /bin/bash
```

Inside the container:
```
cd /root/CenterTrack/src/lib/model/networks/DCNv2
python3 setup.py build develop
cd /root/CenterTrack/src/
python3 demo.py tracking,ddd --load_model ../models/nuScenes_3Dtracking.pth --dataset nuscenes --pre_hm --track_thresh 0.1 --demo ../videos/nuscenes_mini.mp4 --test_focal_length 633
```
The DCNv2 is built from [MatthewHowe_DCNv2](https://github.com/MatthewHowe/DCNv2). Thanks [MatthewHowe](https://github.com/MatthewHowe) for the contribution.
Then you should be able to see the results.

Go to ```/share``` to transfer data between the container and your root system.
